name: medusa_ecommerce

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: medusa_postgres_ecommerce
    restart: unless-stopped
    environment:
      POSTGRES_DB: medusa_store
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_ecommerce:/var/lib/postgresql/data
    networks:
      - medusa_network_ecommerce

  # Redis
  redis:
    image: redis:7-alpine
    container_name: medusa_redis_ecommerce
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - medusa_network_ecommerce

  # THÊM SERVICE NÀY VÀO:
  payment-server:
    build: ../vnpay-api/ # Ví dụ: ./payment-service
    container_name: payment_server_container
    restart: unless-stopped
    ports:
      - "8888:8888"
    environment:
      # Đây là link Frontend (Web bán hàng) của bạn trên Cloudflare
      # Thay bằng link thực tế bạn đang có
      - FRONTEND_URL=http://localhost:3000
    networks:
      - medusa_network_ecommerce

  # Medusa Backend
  medusa:
    build: .
    container_name: medusa_backend_ecommerce
    restart: unless-stopped
    depends_on:
      - postgres
      # - redis
    ports:
      - "9000:9000"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/medusa_store
      - REDIS_URL=redis://redis:6379
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.medusa      
    networks:
      - medusa_network_ecommerce

volumes:
  postgres_data_ecommerce:

networks:
  medusa_network_ecommerce:
    driver: bridge